apiVersion: v2
name: mariadb
description: A Helm chart for MariaDB 10.4
type: application
version: 0.1.1
appVersion: "10.4"
keywords:
  - mariadb
  - mysql
  - database
home: https://mariadb.org
sources:
  - https://github.com/MariaDB/server
maintainers:
  - name: Admin
