apiVersion: v2
name: mariadb
description: A Helm chart for MariaDB 10.6
type: application
version: 0.2.0
appVersion: "10.6"
keywords:
  - mariadb
  - mysql
  - database
home: https://mariadb.org
sources:
  - https://github.com/MariaDB/server
maintainers:
  - name: Admin
