apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app: {{ include "mariadb.name" . }}
    chart: {{ include "mariadb.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.password | b64enc | quote }}
