apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app: {{ include "mariadb.name" . }}
    chart: {{ include "mariadb.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app: {{ include "mariadb.name" . }}
    release: {{ .Release.Name }}
